pub(super) fn assert_clean_restart() {
    let mut terminal = NativePty::spawn(120, 40);
    terminal.wait_for("›");
    terminal.send("quit\n");
    terminal.finish();
}
fn native_terminal_fault_outcomes_exact(fault: &str, capture: &str) {
    let capture = normalized_terminal_capture(capture);
    let expected = match fault {
        "invalid-fault-value" => "터미널 장애 주입 구성 오류\n- kind: InvalidFaultConfiguration\n- effect: NotDispatched\n- retry: FixConfiguration\n- 동작: 터미널 상태를 변경하거나 런타임 요청을 보내지 않았습니다.\n- 다음: RPOTATO_TEST_TERMINAL_FAULT 값을 닫힌 지원 목록으로 고치세요.".to_string(),
        "size-read" => "터미널 크기 확인 실패\n- code: terminal.capability.size-read\n- 동작: 런타임 요청을 보내지 않았습니다.\n- 다음: 읽기 전용 모드를 사용하세요.".to_string(),
        "mode-read" => "터미널 모드 확인 실패\n- code: terminal.capability.mode-read\n- 동작: 모드와 상태를 변경하지 않았습니다.\n- 다음: 터미널 모드를 확인한 뒤 다시 시도하세요.".to_string(),
        "no-echo-set" => "비밀 입력 보호 설정 실패\n- code: terminal.no-echo-set.failed\n- 동작: 비밀값을 읽거나 요청을 보내지 않았습니다.\n- 다음: 무반향 입력을 복구하세요.".to_string(),
        "secret-read" => "비밀 입력 읽기 실패\n- code: terminal.secret-read.failed\n- 동작: 비밀값을 수락하거나 저장하지 않았습니다.\n- 다음: 새 입력으로 다시 시도하세요.".to_string(),
        "frame-write-before-dispatch" => {
            let intent = capture_field(
                &capture,
                "terminal.frame-write.pre-dispatch",
                "intent",
            );
            format!(
                "요청 전 화면 출력 실패\n- code: terminal.frame-write.pre-dispatch\n- intent: {intent}\n- 동작: 런타임 요청을 보내지 않았습니다.\n- 다음: 정본 상태를 다시 읽고 요청하세요."
            )
        }
        "frame-write-after-dispatch" => {
            let intent = capture_field(
                &capture,
                "terminal.frame-write.post-dispatch",
                "intent",
            );
            format!(
                "커밋 후 화면 출력 실패\n- code: terminal.frame-write.post-dispatch\n- intent: {intent}\n- 동작: 요청을 다시 보내지 않습니다.\n- 다음: 영수증을 새로고침하세요."
            )
        }
        other => panic!("unknown native terminal fault oracle: {other}"),
    };
    assert_exact_outcome_block(&capture, &expected, fault);
}

fn native_terminal_denial_block_outcomes_exact(
    capture: &str,
    code: &str,
    workflow_id: &str,
    phase: Option<&str>,
) {
    let capture = normalized_terminal_capture(capture);
    let intent = capture_field(&capture, code, "intent");
    assert!(
        intent.starts_with("intent-tui-"),
        "native denial intent must be generated by the live controller: {intent}"
    );
    let expected = match code {
        "deny.patch.accepted" => format!(
            "패치 적용 거부 완료\n- code: deny.patch.accepted\n- intent: {intent}\n- workflow: {workflow_id}\n- 동작: 소스 변경 없이 취소 상태를 기록했습니다.\n- 다음: 거부 영수증을 확인하세요."
        ),
        "deny.verification.rolled-back" => format!(
            "검증 거부 및 롤백 완료\n- code: deny.verification.rolled-back\n- intent: {intent}\n- workflow: {workflow_id}\n- 동작: 원본 해시를 검증하고 취소 상태를 기록했습니다.\n- 다음: 롤백 영수증을 확인하세요."
        ),
        "deny.blocked.not-pending" => format!(
            "승인 대기 상태가 아니어서 거부 차단\n- code: deny.blocked.not-pending\n- intent: {intent}\n- workflow: {workflow_id}\n- phase: {}\n- 동작: 승인 상태와 효과를 변경하지 않았습니다.\n- 다음: 취소를 사용하거나 정본 상태를 새로고침하세요.",
            phase.expect("not-pending denial requires phase")
        ),
        "deny.blocked.terminal-state" => format!(
            "종료 상태여서 거부 차단\n- code: deny.blocked.terminal-state\n- intent: {intent}\n- workflow: {workflow_id}\n- phase: {}\n- 동작: 종료 상태와 영수증을 변경하지 않았습니다.\n- 다음: 기존 종료 영수증을 확인하세요.",
            phase.expect("terminal denial requires phase")
        ),
        other => panic!("unknown native denial oracle: {other}"),
    };
    assert_exact_outcome_block(&capture, &expected, code);
}

fn assert_exact_outcome_block(capture: &str, expected: &str, context: &str) {
    let expected_lines = expected.lines().collect::<Vec<_>>();
    assert!(expected_lines.len() >= 2, "invalid exact oracle: {context}");
    let marker = expected_lines[1];
    let capture_lines = capture.lines().collect::<Vec<_>>();
    let matches = capture_lines
        .iter()
        .enumerate()
        .filter(|(_, line)| line.trim_start() == marker)
        .map(|(index, _)| index)
        .collect::<Vec<_>>();
    assert!(
        !matches.is_empty(),
        "exact outcome marker missing for {context}\ncapture:\n{capture}"
    );
    for marker_index in matches {
        let start = marker_index
            .checked_sub(1)
            .unwrap_or_else(|| panic!("exact outcome header missing for {context}"));
        let end = start + expected_lines.len();
        assert!(
            end <= capture_lines.len(),
            "exact outcome truncated for {context}\ncapture:\n{capture}"
        );
        let mut actual_lines = capture_lines[start..end].to_vec();
        if actual_lines[0] != expected_lines[0] {
            actual_lines[0] = actual_lines[0]
                .strip_suffix(expected_lines[0])
                .map(|_| expected_lines[0])
                .unwrap_or(actual_lines[0]);
        }
        let actual = actual_lines.join("\n");
        assert_eq!(
            actual, expected,
            "exact outcome block mismatch for {context}\ncapture:\n{capture}"
        );
    }
}

fn normalized_terminal_capture(capture: &str) -> String {
    native_terminal_support::strip_terminal_controls(capture)
        .replace("\r\n", "\n")
        .replace('\r', "\n")
        .lines()
        .map(|line| {
            line.strip_prefix("notice: ")
                .or_else(|| line.strip_prefix("        "))
                .or_else(|| line.strip_prefix("◇ "))
                .or_else(|| {
                    line.strip_prefix("  ")
                        .filter(|rest| rest.starts_with("- "))
                })
                .unwrap_or(line)
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn normalizes_windows_title_and_cursor_control_sequences() {
    let capture =
        "\u{001b}[?25l◇ 결과\n  - 다음: 완료.\u{001b}]0;C:\\rpotato.exe\u{0007}\u{001b}[?25h";
    assert_eq!(normalized_terminal_capture(capture), "결과\n- 다음: 완료.");
}

#[test]
fn conpty_mode_probe_parser_ignores_control_sequences_and_prompt_prefix() {
    let capture = b"\x1b[?9001h\xe2\x80\xba \x1b]0;C:\\rpotato.exe\x07MODE ECHO=1\x1b[?25h\r\n";
    assert_eq!(native_terminal_support::mode_probe_values(capture), ["1"]);
}

fn capture_field(capture: &str, code: &str, field: &str) -> String {
    let marker = format!("- code: {code}");
    let tail = capture
        .split_once(&marker)
        .unwrap_or_else(|| panic!("native capture missing exact code marker {marker}"))
        .1;
    let prefix = format!("- {field}: ");
    tail.lines()
        .find_map(|line| line.trim_start().strip_prefix(&prefix))
        .filter(|value| !value.is_empty())
        .unwrap_or_else(|| panic!("native capture missing {field} after {code}"))
        .to_string()
}
