use super::super::*;

pub(super) fn prepared_approval_members(
    r1: &state::PreparedWorkflowRevision,
    r2: &state::PreparedWorkflowRevision,
    transcript: &transcript::PreparedTranscriptTurn,
    current: &state::PreparedCurrentImage,
    lag: transition::PreparedMember,
    events: &[ledger::LedgerEvent],
) -> Vec<transition::PreparedMember> {
    use transition::{PreparedMember, PreparedMemberBinding, PreparedMemberKind};
    let member = |kind,
                  path: String,
                  schema_version,
                  artifact_id: String,
                  causal_id: Option<String>,
                  event_id: String,
                  bytes_utf8: String,
                  expected_type: &str,
                  expected_identity: Option<String>,
                  role| PreparedMember {
        kind,
        path,
        schema_version,
        binding: PreparedMemberBinding {
            artifact_id: Some(artifact_id),
            causal_id,
            source_key: None,
            event_id: Some(event_id),
        },
        bytes_utf8,
        expected_type: expected_type.to_string(),
        expected_identity,
        readonly: false,
        mode: 0o600,
        ownership: None,
        semantic_role_rank: role,
    };
    vec![
        member(
            PreparedMemberKind::ToolOutput,
            transcript.tool_stored_path.clone(),
            1,
            transcript.tool_artifact_id.clone(),
            Some(events[7].event_id.clone()),
            events[7].event_id.clone(),
            transcript.tool_bytes.clone(),
            "absent",
            None,
            0,
        ),
        member(
            PreparedMemberKind::TranscriptV2,
            transcript.transcript_stored_path.clone(),
            2,
            transcript.record.record_id.clone(),
            Some(transcript.tool_artifact_id.clone()),
            events[8].event_id.clone(),
            transcript.transcript_bytes.clone(),
            "absent",
            None,
            0,
        ),
        member(
            PreparedMemberKind::WorkflowSnapshot,
            r1.snapshot_stored_path.clone(),
            4,
            r1.snapshot_member_id.clone(),
            None,
            events[1].event_id.clone(),
            r1.snapshot_bytes.clone(),
            "absent",
            None,
            0,
        ),
        member(
            PreparedMemberKind::WorkflowSnapshot,
            r2.snapshot_stored_path.clone(),
            4,
            r2.snapshot_member_id.clone(),
            None,
            events[9].event_id.clone(),
            r2.snapshot_bytes.clone(),
            "absent",
            None,
            1,
        ),
        member(
            PreparedMemberKind::WorkflowPointer,
            r1.pointer_stored_path.clone(),
            4,
            r1.pointer_member_id.clone(),
            Some(r1.snapshot_member_id.clone()),
            events[1].event_id.clone(),
            r1.pointer_bytes.clone(),
            "file",
            None,
            0,
        ),
        member(
            PreparedMemberKind::WorkflowPointer,
            r2.pointer_stored_path.clone(),
            4,
            r2.pointer_member_id.clone(),
            Some(r2.snapshot_member_id.clone()),
            events[9].event_id.clone(),
            r2.pointer_bytes.clone(),
            "file",
            None,
            1,
        ),
        member(
            PreparedMemberKind::CurrentImage,
            current.stored_path.clone(),
            2,
            current.artifact_id.clone(),
            Some(r2.snapshot_member_id.clone()),
            events[9].event_id.clone(),
            current.bytes.clone(),
            "file",
            None,
            0,
        ),
        lag,
    ]
}
