use super::manifest::{SkillManifest, EXECUTE_HOOKS, READ_ONLY_HOOKS};

pub const BUILTIN_SKILLS: &[SkillManifest] = &[
    SkillManifest {
        id: "conversation",
        display_name: "Conversation",
        description: "일반 대화와 질문에 부작용 없이 답한다.",
        mode: "read-only",
        required_hooks: READ_ONLY_HOOKS,
        allowed_tools: &[],
        context_requirements: &[],
        evidence_requirements: &[],
        stop_criteria: &["korean_report_passed"],
    },
    SkillManifest {
        id: "fix-test",
        display_name: "Fix Test",
        description: "실패한 테스트 하나를 좁은 범위에서 수정하고 검증한다.",
        mode: "execute",
        required_hooks: EXECUTE_HOOKS,
        allowed_tools: &["read_file", "render_diff", "apply_patch", "run_command"],
        context_requirements: &["test_output", "source_pointer", "package_manifest"],
        evidence_requirements: &["failing_test_before", "passing_test_after"],
        stop_criteria: &[
            "patch_applied",
            "verification_passed",
            "korean_report_passed",
        ],
    },
    SkillManifest {
        id: "explain-error",
        display_name: "Explain Error",
        description: "오류 원인을 코드와 로그 근거로 설명한다.",
        mode: "read-only",
        required_hooks: READ_ONLY_HOOKS,
        allowed_tools: &["read_file", "run_read_only_command"],
        context_requirements: &["error_output", "source_pointer"],
        evidence_requirements: &["source_reference"],
        stop_criteria: &["cause_explained", "korean_report_passed"],
    },
    SkillManifest {
        id: "small-patch",
        display_name: "Small Patch",
        description: "작고 되돌릴 수 있는 패치 하나를 제안한다.",
        mode: "execute",
        required_hooks: EXECUTE_HOOKS,
        allowed_tools: &["read_file", "render_diff", "apply_patch", "run_command"],
        context_requirements: &["target_file", "acceptance_criteria"],
        evidence_requirements: &["diff_review", "targeted_verification"],
        stop_criteria: &[
            "patch_applied",
            "verification_passed",
            "korean_report_passed",
        ],
    },
    SkillManifest {
        id: "code-review",
        display_name: "Code Review",
        description: "버그, 회귀, 테스트 누락을 우선으로 리뷰한다.",
        mode: "review-only",
        required_hooks: READ_ONLY_HOOKS,
        allowed_tools: &["read_file", "run_read_only_command"],
        context_requirements: &["diff_or_files", "test_context"],
        evidence_requirements: &["file_line_reference"],
        stop_criteria: &["findings_ranked", "korean_report_passed"],
    },
    SkillManifest {
        id: "repo-map",
        display_name: "Repo Map",
        description: "저장소 구조와 관련 파일을 읽기 전용으로 매핑한다.",
        mode: "read-only",
        required_hooks: READ_ONLY_HOOKS,
        allowed_tools: &["read_file", "run_read_only_command"],
        context_requirements: &["repo_root"],
        evidence_requirements: &["file_reference"],
        stop_criteria: &["map_reported", "korean_report_passed"],
    },
    SkillManifest {
        id: "benchmark-model",
        display_name: "Benchmark Model",
        description: "모델 후보를 출처 기반 benchmark 계획으로 평가한다.",
        mode: "plan-only",
        required_hooks: READ_ONLY_HOOKS,
        allowed_tools: &["read_file", "run_read_only_command"],
        context_requirements: &["model_manifest", "benchmark_spec"],
        evidence_requirements: &["benchmark_source", "local_result_artifact"],
        stop_criteria: &["benchmark_plan_ready", "korean_report_passed"],
    },
    SkillManifest {
        id: "model-artifact-audit",
        display_name: "Model Artifact Audit",
        description: "모델 artifact 출처, 라이선스, checksum을 검토한다.",
        mode: "read-only",
        required_hooks: READ_ONLY_HOOKS,
        allowed_tools: &["read_file"],
        context_requirements: &["model_source", "license_source", "artifact_manifest"],
        evidence_requirements: &["source_url_or_file", "checksum_record"],
        stop_criteria: &["claims_source_backed", "korean_report_passed"],
    },
    SkillManifest {
        id: "runtime-doctor",
        display_name: "Runtime Doctor",
        description: "runtime state/backend/cache 상태를 진단한다.",
        mode: "read-only",
        required_hooks: READ_ONLY_HOOKS,
        allowed_tools: &["read_file", "run_read_only_command"],
        context_requirements: &["runtime_state", "operation_log"],
        evidence_requirements: &["diagnostic_output"],
        stop_criteria: &["diagnosis_reported", "korean_report_passed"],
    },
    SkillManifest {
        id: "ontology-refresh",
        display_name: "Ontology Refresh",
        description: "프로젝트 ontology pointer와 source evidence를 갱신한다.",
        mode: "plan-only",
        required_hooks: READ_ONLY_HOOKS,
        allowed_tools: &["read_file"],
        context_requirements: &["ontology_source", "source_pointer"],
        evidence_requirements: &["source_reference", "confidence_record"],
        stop_criteria: &["ontology_delta_ready", "korean_report_passed"],
    },
    SkillManifest {
        id: "release-check",
        display_name: "Release Check",
        description: "릴리즈 전 문서, 테스트, 정책 누락을 점검한다.",
        mode: "review-only",
        required_hooks: READ_ONLY_HOOKS,
        allowed_tools: &["read_file", "run_read_only_command"],
        context_requirements: &["release_scope", "test_results"],
        evidence_requirements: &["check_result"],
        stop_criteria: &["release_findings_reported", "korean_report_passed"],
    },
];

pub fn find_skill(id: &str) -> Option<&'static SkillManifest> {
    BUILTIN_SKILLS.iter().find(|skill| skill.id == id)
}
